import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faUser,
    faAngleLeft,
    faAngleRight,
    faAdd,
    faUserEdit,
    faUserPlus,
    faTrash,
    faFloppyDisk,
    faScrewdriverWrench,
    faPlusCircle,
    faPen,
    faSortDesc,
    faSortAsc,
    faTable,
    faTableColumns,
    faHeading,
    faAngleUp,
    faAngleDown,
    faTimes,
    faFilePdf,
    faEye,
    faCircleCheck,
    faGears,
    faFileArrowDown,
    faClone,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faAngleLeft,
    faUser,
    faAngleRight,
    faAdd,
    faUserEdit,
    faUserPlus,
    faTrash,
    faFloppyDisk,
    faScrewdriverWrench,
    faPlusCircle,
    faPen,
    faSortDesc,
    faSortAsc,
    faTable,
    faTableColumns,
    faHeading,
    faAngleUp,
    faAngleDown,
    faTimes,
    faFilePdf,
    faEye,
    faCircleCheck,
    faGears,
    faFileArrowDown,
    faClone
);

export default FontAwesomeIcon;